# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rails"
gem 'bootstrap'
gem 'sqlite3'
gem 'jquery-rails'

gem 'spring', group: :development
